<Project>
  <PropertyGroup>
    <TargetPlatformIdentifier Condition="'$(TargetPlatformIdentifier)' == ''">Windows</TargetPlatformIdentifier>
    <TargetPlatformVersion Condition="'$(TargetPlatformVersion)' == ''">7.0</TargetPlatformVersion>
    <TargetPlatformMoniker Condition="'$(TargetPlatformMoniker)' == ''">Windows,Version=7.0</TargetPlatformMoniker>
    <TargetPlatformSdkPath Condition="'$(TargetPlatformSdkPath)' == ''">C:\Program Files (x86)\Windows Kits\10\</TargetPlatformSdkPath>
    <TargetPlatformDisplayName Condition="'$(TargetPlatformDisplayName)' == ''">Windows SDK</TargetPlatformDisplayName>
    <RestoreIgnoreFailedSources>true</RestoreIgnoreFailedSources>
    <NuGetAudit>false</NuGetAudit>
    <RestoreProjectStyle Condition="'$(MSBuildProjectName)' == 'Mediclin.UI' Or '$(MSBuildProjectName)' == 'Mediclin.Business' Or '$(MSBuildProjectName)' == 'Mediclin.Data'">None</RestoreProjectStyle>
    <RestoreSources Condition="'$(MSBuildProjectName)' == 'Mediclin.UI' Or '$(MSBuildProjectName)' == 'Mediclin.Business' Or '$(MSBuildProjectName)' == 'Mediclin.Data'"></RestoreSources>
    <DefaultItemExcludes>$(DefaultItemExcludes);**\obj*\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Google.Protobuf">
      <HintPath>$(MSBuildThisFileDirectory)libs\Google.Protobuf.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="K4os.Compression.LZ4.Streams">
      <HintPath>$(MSBuildThisFileDirectory)libs\K4os.Compression.LZ4.Streams.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="K4os.Compression.LZ4">
      <HintPath>$(MSBuildThisFileDirectory)libs\K4os.Compression.LZ4.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="K4os.Hash.xxHash">
      <HintPath>$(MSBuildThisFileDirectory)libs\K4os.Hash.xxHash.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="BouncyCastle.Crypto">
      <HintPath>$(MSBuildThisFileDirectory)libs\BouncyCastle.Crypto.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Configuration.ConfigurationManager">
      <HintPath>$(MSBuildThisFileDirectory)libs\System.Configuration.ConfigurationManager.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.IO.Pipelines">
      <HintPath>$(MSBuildThisFileDirectory)libs\System.IO.Pipelines.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe">
      <HintPath>$(MSBuildThisFileDirectory)libs\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Security.Cryptography.ProtectedData">
      <HintPath>$(MSBuildThisFileDirectory)libs\System.Security.Cryptography.ProtectedData.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Security.Permissions">
      <HintPath>$(MSBuildThisFileDirectory)libs\System.Security.Permissions.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Text.Encoding.CodePages">
      <HintPath>$(MSBuildThisFileDirectory)libs\System.Text.Encoding.CodePages.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Threading.Tasks.Extensions">
      <HintPath>$(MSBuildThisFileDirectory)libs\System.Threading.Tasks.Extensions.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <None Include="$(MSBuildThisFileDirectory)libs\*.dll">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </None>
  </ItemGroup>
</Project>
