analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3467762,"name"\:"First Project","teamId"\:3452067,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3490589,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3452067,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
