<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mediclin.Business\Mediclin.Business.csproj" />
    <ProjectReference Include="..\Mediclin.Data\Mediclin.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MySql.Data">
      <HintPath>..\libs\MySql.Data.dll</HintPath>
    </Reference>
    <Reference Include="BCrypt.Net-Next">
      <HintPath>..\libs\BCrypt.Net-Next.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml" />
    <Page Include="Resources\*.xaml" />
    <Page Include="Views\**\*.xaml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
